### ISSUE TITLE
Meeting Agenda: Sunday, July 31st, 17:00 UTC

### ISSUE THREAD

**Issue by anonimal** [monero-project/kovri#216]
**By submitting this issue, I confirm the following:**

- I have read and understood the [contributor guide](https://github.com/monero-project/kovri/blob/master/doc/CONTRIBUTING.md).
- I have checked that the issue I am reporting can be replicated or that the feature I am suggesting is not present.
- I have checked opened or recently closed [pull requests](https://github.com/monero-project/kovri/pulls) for existing solutions/implementations to my issue/suggestion.

*Place an X inside the bracket to confirm*
- [X] I confirm.

---

### Date and location:
- 17:00 (UTC)
- IRC: [Freenode](https://webchat.freenode.net/) | [OFTC](https://webchat.oftc.net/) | Irc2P | [Slack](https://monero.slack.com)
  - ```#kovri-dev```

### Proposed meeting items:
1. Greetings
2. Brief review of what's been completed since the previous meeting
3. Discuss Kovri logo
4. Closing #271 
5. Closing #226 
6. Closing #105 
7. Closing #46 
8. Closing #27 
9. Any additional meeting items
10. Confirm next meeting date/time

Notes:
- #kovri-dev and #monero-dev will be relayed to each other through the duration of the meeting
- Meeting log will be posted to https://getmonero.org/blog/tags/dev%20diaries

**Comment by anonimal** [comment]
I'm adding ```Discuss Kovri logo``` to agenda.

I think that nearly every meeting we've had after our first one has been very work-oriented (mabye *too much* work-oriented?). I also think that maybe some lighter creative discussion could give us some much-needed enthusiasm.

Yes, I would also like to continue to discuss the myriad of issues we have, but now that ```#monero-dev``` is more involved, a new logo idea could generate some more community interest and give us a more definitive identity.

**Comment by anonimal** [comment]
Adding ```Discuss deleting branch development and working solely from master```.

IIRC, *every* Kovri contributor (since first Kovri commit) has, at one point or another, mistakenly or unknowingly PR'd to branch master instead of development. When that happens, I end up having to ask to reopen and then give lengthy reasoning why and then link to the contributing guide.

I'd like to re-discuss a master-only workflow and clearly establish that pre-alpha is pre-alpha. Also, I think that we've been very careful (or have tried to be) about merging any terribly breaking code, so branch development hasn't had much use IMHO.

**Comment by rakhimov** [comment]
Glad to know that I am not the only one confused with PR to master instead of develop.

I am not fully aware what your project users expect,
but I would suggest to keep the current model as: http://nvie.com/posts/a-successful-git-branching-model/

The only fix needed to prevent people from getting a wrong base for PRs
is to make ``development`` branch the default branch in GitHub repo settings.

**Comment by fluffypony** [comment]
@rakhimov one of the reasons we have the dev branch is so that people cloning and building from the repo build stable by default. Correct me if I'm wrong, but if we change the default branch in GitHub to ```development``` won't that then mean it's the default branch when you clone the repo?

We basically have to consider that *at least* 90% of the time people hitting the repo on GitHub are there to clone + build, and 10% of the time (at most;) they'll be wanting to PR to it. I look forward to hearing your thoughts on how we can improve this process and make it easier for contributors!

**Comment by rakhimov** [comment]
@fluffypony Yes, it looks like there's a conflict, and sadly, the user is always right.
On the other hand, the ones who clone and build are savvy folks who can checkout the recent stable release tag or branch.
Maybe for most users, the recommended way to get the most stable (verified with hash) release
is to get some official tarball from your release website, SF, or GitHub release page.

Another approach is to add "I am NOT basing this PR on **master** branch" clause into your PR template
so that contributors don't trip on this common catch.

**Comment by fluffypony** [comment]
> Another approach is to add "I am NOT basing this PR on master branch" clause into your PR template so that contributors don't trip on this common catch.

I like that idea - great suggestion!

**Comment by anonimal** [comment]
> Correct me if I'm wrong, but if we change the default branch in GitHub to development won't that then mean it's the default branch when you clone the repo?

Yes, that is correct.

> Another approach is to add "I am NOT basing this PR on master branch" clause into your PR template so that contributors don't trip on this common catch.

I'll add that to #233

> I am not fully aware what your project users expect, but I would suggest to keep the current model as: http://nvie.com/posts/a-successful-git-branching-model/

The problem with keeping our current flow is that it doesn't recognize our [C4](https://github.com/monero-project/kovri/blob/master/doc/CONTRIBUTING.md):

- The project SHALL have one branch ("master") that always holds the latest in-progress version and SHOULD always build.
- The project SHALL NOT use topic branches for any reason. Personal forks MAY use topic branches.

*And*, our C4 makes a great case: all flippant or unstable work can be done in forks - as we use a strict fork-and-pull methodology. In fact, that is what we are currently doing with our [SSU refactor](https://github.com/einmbyte/kovri/tree/ssu).

[bitmonero](https://github.com/anonimal/bitmonero) has recently made the decision to drop branch ```development``` and I would like to follow suit.  When the time comes to have a release (of any kind), we can use tags and point-out that fact in the README and, of course, we will make tarballs and have binaries available as well.

**Comment by EinMByte** [comment]
It's possible that I will not be able to make the meeting (or be late).

**Comment by anonimal** [comment]
Damn 😞, I hope you can make it. If you have any ideas regarding 3. or 4., please share!

**Comment by fluffypony** [comment]
I've just had something come up that will affect my ability to attend; would it be useful to @EinMByte if we reschedule for next week Sunday?

**Comment by EinMByte** [comment]
@fluffypony I won't be around next week, so don't move it for me.

**Comment by anonimal** [comment]
After seeing the results of an attendance inquiry on ```#monero-dev```, I think it would be best to simply move this agenda to our next meeting which is two weeks from today. Does anyone object?

**Comment by anonimal** [comment]
Postponing the meeting. I or someone else will change the title to the new meeting date once a date is confirmed.

**Comment by anonimal** [comment]
Inter-project comms seem a bit irregular at the moment. Scheduling for the 31st.

**Comment by anonimal** [comment]
Meeting log: https://paste.fedoraproject.org/398905/99880741/raw/
