### ISSUE TITLE
Clarify coding style deviations from the Google style

### ISSUE THREAD

**Issue by rakhimov** [monero-project/kovri#238]
**By submitting this issue, I confirm the following:**

- I have read and understood the [contributor guide](https://github.com/monero-project/kovri/blob/master/doc/CONTRIBUTING.md).
- I have checked that the issue I am reporting can be replicated or that the feature I am suggesting is not present.
- I have checked opened or recently closed [pull requests](https://github.com/monero-project/kovri/pulls) for existing solutions/implementations to my issue/suggestion.

*Place an X inside the bracket to confirm*
- [x] I confirm.

---
From an outsider perspective with some experience with the Google style code,
I observe some common non-Google style conventions in the Kovri code.
(always breaking function parameters and arguments,
 no more than one statement on one line,
 unaligned multi-argument breaks,
 one-space indentation in class declaration,
 filenames and extensions (cpp vs. cc), etc.)

Since the codebase in the style transition state,
it is not clear which conventions are here to stay.

It would be nice to have the style differences clarified in the contributor documentation.
In addition, the clang-format [options](http://clang.llvm.org/docs/ClangFormatStyleOptions.html)
needs to be modified to leverage the automated tools for this tedious task.

**Comment by anonimal** [comment]
When we started the project we decided to adhere to Google's style but only within reason since doing a complete guide refactor was not reasonable nor did we like certain conventions proposed by Google.

Many of the differences you've mentioned appear to be covered in our [style guide](https://github.com/monero-project/kovri/blob/master/doc/STYLE.md) (also, IIRC, one-space ident for class declarations are caught by cpplint).

If you take a look at some of our newer code (like [here](https://github.com/EinMByte/kovri/pull/1) for example), you can get a feel for logic and consistency of style. There's not much to it actually but we do welcome any clang format options or uncrustify config if that makes things easier. 

We also welcome any thoughts on how we can improve the [style guide's](https://github.com/monero-project/kovri/blob/master/doc/STYLE.md) language for consistency.

**Comment by anonimal** [comment]
Note: we haven't spent much time in this area in quite a while so keeping up with Google's style since last November has been on the back-burner. I also see some areas for improvement so you're welcome to make any changes you'd like and PR.
