### ISSUE TITLE
Swapout ref10 from SUPERCOP with TweetNaCl

### ISSUE THREAD

**Issue by anonimal** [monero-project/kovri#485]
**By submitting this issue, I confirm the following:**

- I have read and understood the [contributor guide](https://github.com/monero-project/kovri/blob/master/doc/CONTRIBUTING.md).
- I have checked that the issue I am reporting can be replicated or that the feature I am suggesting is not present.
- I have checked opened or recently closed [pull requests](https://github.com/monero-project/kovri/pulls) for existing solutions/implementations to my issue/suggestion.

*Place an X inside the bracket to confirm*
- [X] I confirm.

---

The use of TweetNaCl has been discussed in the kovri meeting and several times in monero's meetings. Any objections or discussion should be noted in this issue.

**Edit**: ~~An incredibly easy thing to do~~, *Theoretically*, an incredibly easy thing to do **but**, as it turns out, implementation-wise, will require far more work because of how we use polymorphism for all verifying + signing (and a few other issues).

**Edit**: my personal *meh* moment is the amount of work to implement versus the trade-off benefits - but I do like the audit-ability factor. Also, closing this issue will resolve #345 and we also wouldn't need to use cryptopp for hashing (so that's a plus). For now, I'll unassign myself but will most likely be the one that gets to this - though @olarks has expressed an interest so I encourage more developers to get involved.

**Edit**: Note: this is still only a proposal. Does @fluffypony @EinMByte @luigi1111 @moneromooo-monero @hyc @NanoAkron @vtnerd @rakhimov @olarks or anyone else have any input on the issue?

**Comment by luigi1111** [comment]
What are you using now? What functions does Kovri require? I'm quite uninformed here relative to wallet and daemon requirements.

**Comment by anonimal** [comment]
@luigi1111 in terms of general signing usage, used in lease-sets/destinations/router idents/transports: [these](https://github.com/monero-project/kovri/blob/master/src/core/crypto/impl/supercop/ed25519/ed25519_ref10.h) as implemented [here](https://github.com/monero-project/kovri/blob/master/src/core/crypto/impl/supercop/signature.cc) and [here](https://github.com/monero-project/kovri/blob/master/src/core/crypto/signature_base.h) and [here](https://github.com/monero-project/kovri/blob/master/src/core/router/identity.cc) (I have to mention #366) and [here](https://github.com/monero-project/kovri/blob/master/src/core/router/transports/session.h#L82-L89). Also see [Moneropedia: lease-set](https://getmonero.org/knowledge-base/moneropedia/lease-set), [Moneropedia: destination](https://getmonero.org/knowledge-base/moneropedia/destination), [Moneropedia: I2NP](https://getmonero.org/knowledge-base/moneropedia/i2np) and everything else that's in [Moneropedia: Kovri](https://getmonero.org/knowledge-base/moneropedia/kovri) (including all the java I2P specification links), maybe this [small glossery](https://geti2p.net/en/about/glossary) too. Other I2P details [here](https://geti2p.net/spec/common-structures#signingpublickey) and [here](https://geti2p.net/spec/cryptography#eddsa-25519) but the various specifications on their website may provide other details that aren't currently covered in Moneropedia (in terms of *why* and *where* we sign).

**Comment by anonimal** [comment]
@luigi1111 in case you were asking for the ref10 impl details: [open](https://github.com/monero-project/kovri/blob/master/src/core/crypto/impl/supercop/ed25519/open.cc), [keypair](https://github.com/monero-project/kovri/blob/master/src/core/crypto/impl/supercop/ed25519/keypair.cc), [sign](https://github.com/monero-project/kovri/blob/master/src/core/crypto/impl/supercop/ed25519/sign.cc), [hash](https://github.com/monero-project/kovri/blob/master/src/core/crypto/impl/supercop/ed25519/crypto_hash_sha512.h), and [cryptopp hash](https://github.com/monero-project/kovri/blob/master/src/core/crypto/impl/cryptopp/hash.cc).

**Comment by olarks** [comment]
I think the conciseness of the TweetNaCl library would be greatly valuable for Kovri to remain straightforward to audit. Currently its only function would be ed25519 signing operations and sha512 hashing. Obviously if there was ever consensus among the i2p community to change aes256 to another cipher(if aes256 was ever deemed inappropriate/unsafe), xsalsa20 is right there which could pick up the slack for aes256(being notably faster and getting much more rounds for increased security).

**Comment by coneiric** [comment]
@olarks are you still working on this? If so, I would like to help.

**Comment by anonimal** [comment]
Note: now that https://github.com/weidai11/cryptopp/pull/566 has been merged, we will simply use crypto++'s interface!

**Comment by noloader** [comment]
@anonimal, @coneiric, @olarks, @luigi1111

Sorry to jump on your report.

We renamed `nacl.h` to `naclite.h` to avoid name collisions with other libraries. I got cold feet when I started thinking about the bug reports we would catch because of the confusion. Also see [Commit 8ffd165c7a59](https://github.com/weidai11/cryptopp/commit/8ffd165c7a59).

Earlier we added three functions to Bernstein's gear: `crypto_box_unchecked`,  `crypto_box_open_unchecked` and `crypto_box_beforenm_unchecked`. The unchecked version do _not_ check for small order elements. They should provide interop needed for downlevel versions of libraries and protocols. Also see [Commit 0bb73e7035b1](https://github.com/weidai11/cryptopp/commit/0bb73e7035b1).

Interop problems will likely occur for folks like Ethereum and Monero who are providing the high level protocols. Also see Hopwood's comments at libsodium's [Commit afabd7e7386e](https://github.com/jedisct1/libsodium/commit/afabd7e7386e).

Our next tasks are to (1) get the interfaces wired into the benchmarks so we can start measuring performance (and changes), (2) get the interfaces wrapped so they act like Crypto++ objects. As a (3) I would like to put together a script that extracts what we need from libsodium so we always have something that (a) performs well and (b) is always up to date.
