### ISSUE TITLE
ArchLinux AUR integration

### ISSUE THREAD

**Issue by KanediasTheMaker** [monero-project/kovri#71]
There's already i2pd packaged in AUR, adding kovri should be similar.
See https://aur.archlinux.org/packages/i2pd/
PKGBUILD: https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=i2pd

**Comment by anonimal** [comment]
Thank you for the ticket but no, it shouldn't; as we are still in pre-alpha.

i2pd should *not* be packaged. i2pd should not be used by anyone for any serious anonymity. i2pd still has at least several unresolved 0day's and a lead developer who truly doesn't care about what he's doing in terms of security and quality assurance.

Closing as "won't fix" because when we do package, creating appropriate distro packages will be an obvious thing to do and Arch is already on the agenda.

**Comment by xcps** [comment]
Anonimal, but you use i2pd code!!!! What about to make truly yours secure router?

**Comment by anonimal** [comment]
@xcps We've resolved (and are still currently resolving) gaps in implementation and glaring security issues that were brought to us with i2pd. With time, these issues will be resolved and the differences between the two codebases will be ever more distinct.

Don't forget: most of the code simply carries out predetermined specification, so the question of unique ingenuity is no longer a question but rather; how much and how well a specification is carried out. Our [FAQ.md](https://github.com/monero-project/kovri/blob/master/FAQ.md) also helps explain how we create a more secure router.

i2pd's decision to release while ignoring these issues is a silly, stupid path that hurt a person's anonymity; but this is the path they are choosing. Our path is yet another difference between these two projects.
